export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const UPDATE_AUTH_PROGRESS = 'UPDATE_AUTH_PROGRESS';

export const AUTH_LOADING = 'AUTH_LOADING';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_APARTMENT_SUCCESS = 'GET_APARTMENT_SUCCESS';
export const GET_APARTMENT_ERROR = 'GET_APARTMENT_ERROR';

export const GET_SHARED_SUCCESS = 'GET_SHARED_SUCCESS';
export const GET_SHARED_ERROR = 'GET_SHARED_ERROR';

export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_ERROR = 'GET_ALL_BLOG_ERROR';
export const BLOG_LOADING = 'BLOG_LOADING';

export const TOGGLE_LIGHT_BOX = 'TOGGLE_LIGHT_BOX';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';

export const UPLOAD_LOADING = 'UPLOAD_LOADING';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';

export const TOGGLE_DONE_MODAL = 'TOGGLE_DONE_MODAL';

export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const SEND_REQUEST_ERROR = 'SEND_REQUEST_ERROR';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_LOADING = 'SEARCH_LOADING';

export const PAGE_LOADING = 'PAGE_LOADING';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const FEATURE_ERROR = 'FEATURE_ERROR';
export const FEATURE_SUCCESS = 'FEATURE_SUCCESS';
export const FEATURE_MESSAGE = 'FEATURE_MESSAGE';
export const FEATURE_DATA = 'FEATURE_DATA';
export const FEATURE_LOADING = 'FEATURE_LOADING';
export const FEATURE_IMAGE_DONE = 'FEATURE_IMAGE_DONE';
export const FEATURE_PROGRESS = 'FEATURE_PROGRESS';

export const DETAIL_LOADING = 'DETAIL_LOADING';
export const TOGGLE_ADD_NUMBER = 'TOGGLE_ADD_NUMBER';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';


// View
export const SET_DASHBOARD_VIEW = 'SET_DASHBOARD_VIEW';


// Agnet
export const ADD_AGENT = 'ADD_AGENT';
export const AGENT_LOADING = 'AGENT_LOADING';
export const SET_AGENT_LIST = 'SET_AGENT_LIST';
export const EDIT_AGENT_ACCOUNT = 'EDIT_AGENT_ACCOUNT';
export const UPDATE_AGENT_PROGRESS = 'UPDATE_AGENT_PROGRESS';
export const SET_AGENT_PROPERTIES = 'SET_AGENT_PROPERTIES';
export const LISTING_LOADING = 'LISTING_LOADING';
export const LISTING_STATUS = 'LISTING_STATUS';